Review controller
sylviabbt/fixer-airbnb pull request #6
Opened 2019-04-02 10:05 UTC by sylviabbt

2019-04-02 10:06 UTC, sylviabbt commented
reviews-controller, again tbc after the views

2019-04-03 02:10 UTC, ivyyu10 commented on app/controllers/reviews_controller.rb
> +    params.require(:review).permit(:content, :rating, :booking_id)
we can also remove booking_id on this but need to create a few more lines above in the create (similar to the bookings controller) let's have a look through together and test!

2019-04-03 02:12 UTC, ivyyu10 requested changes
Please add the views pages with controllers so we can test with front end right away before we style!

2019-04-03 04:35 UTC, sylviabbt commented
changes in controller done
also removed double nesting from the routes
@ivyyu10

2019-04-03 06:20 UTC, ivyyu10 approved these changes

2019-04-03 06:20 UTC, merged